# Step 1: Importing NumPy
**Description:** Import the NumPy library, which is essential for numerical operations in Python.
**Concept:** NumPy provides support for arrays, matrices, and mathematical functions.
**Function:** `import numpy as np` imports NumPy and gives it the alias `np` for easier usage throughout the notebook.
**Prerequisite:** NumPy must be installed in your Python environment.

In [8]:
import numpy as np

# Step 2: Creating a 1D Array
**Description:** Create a 1-dimensional NumPy array with values from 11 to 20.
**Concept:** Arrays are the core data structure in NumPy, allowing efficient storage and manipulation of numerical data.
**Function:** `np.arange(11,21)` generates numbers from 11 to 20. `arr` stores the array.
**Prerequisite:** NumPy must be imported as `np`.

In [9]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Step 3: Accessing an Array Element by Index
**Description:** Retrieve the value at index 6 of the array `arr`.
**Concept:** NumPy arrays are zero-indexed. Accessing elements by index is fundamental for data manipulation.
**Function:** `arr[6]` returns the 7th element of the array.
**Prerequisite:** The array `arr` must be defined.

In [10]:
arr[6]

np.int64(17)

# Step 4: Accessing Another Array Element by Index
**Description:** Retrieve the value at index 9 of the array `arr`.
**Concept:** Indexing allows you to access specific elements in an array.
**Function:** `arr[9]` returns the 10th element of the array.
**Prerequisite:** The array `arr` must be defined.

In [5]:
arr[9]

np.int64(20)

# Step 5: Slicing a 1D Array
**Description:** Extract a subarray from index 1 to 4 (inclusive of 1, exclusive of 5).
**Concept:** Slicing allows you to select a range of elements from an array using the syntax `arr[start:end]`.
**Function:** `arr[1:5]` returns elements at indices 1, 2, 3, and 4.
**Prerequisite:** The array `arr` must be defined.

In [6]:
arr[1:5]

array([12, 13, 14, 15])

# Step 6: Slicing from Start to Index
**Description:** Extract a subarray from the beginning up to index 4 (exclusive).
**Concept:** Omitting the start index defaults to 0. Slicing is a powerful way to access parts of an array.
**Function:** `arr[:5]` returns elements at indices 0, 1, 2, 3, and 4.
**Prerequisite:** The array `arr` must be defined.

In [7]:
arr[:5]

array([11, 12, 13, 14, 15])

# Step 7: Slicing the Entire Array
**Description:** Extract all elements from the array.
**Concept:** Using `:` with no start or end returns the whole array.
**Function:** `arr[:]` returns all elements.
**Prerequisite:** The array `arr` must be defined.

In [8]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Step 8: Slicing with a Step
**Description:** Extract every second element from index 3 to the end.
**Concept:** Slicing can include a step value: `arr[start:end:step]`.
**Function:** `arr[3::2]` returns elements at indices 3, 5, 7, etc.
**Prerequisite:** The array `arr` must be defined.

In [11]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

# Step 9: Creating and Reshaping a 2D Array
**Description:** Create a 2D array with values from 1 to 30, reshaped into 6 rows and 5 columns.
**Concept:** Reshaping changes the dimensions of an array without changing its data. 2D arrays are useful for representing matrices and tables.
**Function:** `np.arange(1,31).reshape(6,5)` creates a 2D array of shape (6,5).
**Prerequisite:** NumPy must be imported as `np`.

In [11]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Step 10: Accessing a Row in a 2D Array
**Description:** Retrieve the second row of the 2D array `arr`.
**Concept:** In 2D arrays, rows and columns can be accessed using indices. `arr[row_index]` returns the specified row.
**Function:** `arr[1]` returns the second row (indexing starts at 0).
**Prerequisite:** The 2D array `arr` must be defined.

In [14]:
arr[1]

array([ 6,  7,  8,  9, 10])

# Step 11: Accessing an Element in a 2D Array
**Description:** Retrieve the element at the first row and first column of the 2D array `arr`.
**Concept:** Elements in 2D arrays are accessed using two indices: `arr[row, column]`.
**Function:** `arr[0,0]` returns the element at the top-left corner.
**Prerequisite:** The 2D array `arr` must be defined.

In [15]:
arr[0,0]

np.int64(1)

# Step 12: Accessing a Specific Element in a 2D Array
**Description:** Retrieve the element at the first row and last column of the 2D array `arr`.
**Concept:** You can access any element in a 2D array using its row and column indices.
**Function:** `arr[0,4]` returns the element in the first row, fifth column.
**Prerequisite:** The 2D array `arr` must be defined.

In [17]:
arr[0,4]

np.int64(5)

# Step 12: Accessing a Specific Element in a 2D Array
**Description:** Retrieve the element at the first row and last column of the 2D array `arr`.
**Concept:** You can access any element in a 2D array using its row and column indices.
**Function:** `arr[0,4]` returns the element in the first row, fifth column.
**Prerequisite:** The 2D array `arr` must be defined.

In [12]:
slice = arr[0:2, 1:3]
slice

array([[2, 3],
       [7, 8]])

# Step 14: Slicing the Lower-Right Submatrix
**Description:** Extract the submatrix from row 3 to the end and column 3 to the end of the 2D array `arr`.
**Concept:** Slicing with open-ended indices allows you to select all remaining rows and columns from a starting point.
**Function:** `arr[3:, 3:]` returns the lower-right submatrix.
**Prerequisite:** The 2D array `arr` must be defined.

In [15]:
slice2 = arr[3: , 3: ]
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

# Step 15: Selecting a Column from a 2D Array
**Description:** Retrieve all elements from the third column of the 2D array `arr`.
**Concept:** You can select an entire column by specifying all rows and a single column index: `arr[:, column_index]`.
**Function:** `arr[:, 2]` returns the third column.
**Prerequisite:** The 2D array `arr` must be defined.

In [16]:
arr[: , 2]

array([ 3,  8, 13, 18, 23, 28])

# Step 16: Creating a New 1D Array
**Description:** Create a 1-dimensional NumPy array with values from 21 to 30.
**Concept:** Arrays can be redefined or created as needed for different operations. This step demonstrates array creation with a new range.
**Function:** `np.arange(21,31)` generates numbers from 21 to 30. `arr` stores the array.
**Prerequisite:** NumPy must be imported as `np`.

In [18]:
arr = np.arange(21,31)
arr

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# Step 17: Creating a Boolean Index for Even Numbers
**Description:** Generate a boolean array indicating which elements in `arr` are even.
**Concept:** Boolean indexing allows you to filter arrays based on conditions. The result is an array of True/False values.
**Function:** `arr % 2 == 0` returns True for even elements, False otherwise. `bool_index` stores the result.
**Prerequisite:** The array `arr` must be defined.

In [24]:
bool_index = arr%2 == 0
bool_index

array([ True,  True,  True,  True,  True])

# Step 18: Selecting Even Elements Using Boolean Indexing
**Description:** Use the boolean index to extract all even elements from the array `arr`.
**Concept:** Boolean indexing is a powerful way to select elements that meet a condition.
**Function:** `arr[bool_index]` returns all even elements in `arr`.
**Prerequisite:** The array `arr` and `bool_index` must be defined.

In [25]:
bool_index = arr%2 == 0
arr[bool_index]

array([22, 24, 26, 28, 30])

# Step 19: Reassigning the Array to Even Elements
**Description:** Update the array `arr` to contain only the even elements previously selected.
**Concept:** Arrays can be reassigned to new values, allowing you to focus on subsets of data for further analysis.
**Function:** `arr = arr[bool_index]` updates `arr` to only even numbers.
**Prerequisite:** The array `arr` and `bool_index` must be defined.

In [26]:
arr = arr[bool_index]
arr

array([22, 24, 26, 28, 30])