# Importing NumPy
**Concept:** NumPy is the foundational library for numerical operations in Python, providing support for arrays, matrices, and mathematical functions.
**How it works:** The statement `import numpy as np` imports the library and assigns it the alias `np` for convenience.
**Extra Tips:** Always import NumPy at the start of your notebook. If you get an ImportError, install NumPy using `pip install numpy`.

In [1]:
import numpy as np

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

# Element-wise Addition
**Concept:** NumPy supports element-wise arithmetic operations, meaning each element in one array is added to the corresponding element in another array.
**How it works:** `a1 + a2` adds each element of `a1` to the corresponding element of `a2`.
**Extra Tips:** Arrays must be of the same shape for element-wise operations. If shapes differ, NumPy will attempt broadcasting.

In [3]:
a1+a2

array([ 7,  9, 11, 13, 15])

# Element-wise Subtraction
**Concept:** Subtraction is performed element-wise, subtracting each element in one array from the corresponding element in another.
**How it works:** `a1 - a2` subtracts each element of `a2` from `a1`.
**Extra Tips:** Useful for calculating differences between datasets. Arrays must be compatible in shape.

In [4]:
a1-a2

array([-5, -5, -5, -5, -5])

# Element-wise Multiplication
**Concept:** Each element in one array is multiplied by the corresponding element in another array.
**How it works:** `a1 * a2` multiplies each element of `a1` with the corresponding element of `a2`.
**Extra Tips:** This is not matrix multiplication; it's element-wise. For matrix multiplication, use `@` or `np.dot`.

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

# Element-wise Division
**Concept:** Division is performed element-wise, dividing each element in one array by the corresponding element in another.
**How it works:** `a1 / a2` divides each element of `a1` by the corresponding element of `a2`.
**Extra Tips:** Watch out for division by zero. Use integer division (`//`) for whole number results.

In [6]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

# Element-wise Integer Division
**Concept:** Integer division returns the whole number part of the division for each element pair in the arrays.
**How it works:** `a1 // a2` divides each element of `a1` by the corresponding element of `a2` and returns the integer part.
**Extra Tips:** Useful for tasks where you need to ignore the remainder. Be careful with negative numbers, as integer division rounds towards negative infinity.

In [7]:
a1//a2

array([0, 0, 0, 0, 0])

# Element-wise Power
**Concept:** Raises each element in one array to the power of the corresponding element in another array.
**How it works:** `a1 ** a2` computes `a1[i]` raised to the power of `a2[i]` for each index `i`.
**Extra Tips:** Can result in very large numbers quickly. Use with caution for large arrays or high exponents.

In [8]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

# Converting Lists to Arrays
**Concept:** NumPy arrays are more efficient than Python lists for numerical operations.
**How it works:** `np.array(l)` converts a Python list `l` into a NumPy array `arr`.
**Extra Tips:** Arrays support vectorized operations, while lists do not. Always convert lists to arrays before performing mathematical operations.

In [9]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)

# Broadcasting in NumPy
**Concept:** Broadcasting allows NumPy to perform operations between arrays of different shapes by automatically expanding the smaller array.
**How it works:** `arr + 10` adds 10 to each element of the array `arr`. The scalar 10 is broadcasted to match the shape of `arr`.
**Extra Tips:** Broadcasting is powerful but can lead to unexpected results if shapes are not compatible. Always check array shapes before broadcasting.

In [10]:
arr + 10

array([11, 12, 13, 14, 15])

# Creating and Reshaping Arrays
**Concept:** NumPy arrays can be reshaped to different dimensions, allowing for flexible data organization.
**How it works:** `np.arange(1,26).reshape(5,5)` creates a 1D array of numbers from 1 to 25 and reshapes it into a 5x5 2D array.
**Extra Tips:** The total number of elements must remain the same when reshaping. Use `.reshape()` to convert between 1D, 2D, and higher dimensions.

In [11]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Broadcasting with 2D Arrays
**Concept:** Broadcasting works with multi-dimensional arrays, allowing you to add a scalar to every element in a 2D array.
**How it works:** `arr2 + 10` adds 10 to each element of the 5x5 array `arr2`.
**Extra Tips:** Broadcasting simplifies code and avoids explicit loops. Always check shapes to avoid unexpected results.

In [12]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

# Creating Arrays with arange
**Concept:** `np.arange` generates arrays with evenly spaced values within a given interval.
**How it works:** `np.arange(1,31)` creates a 1D array with values from 1 to 30.
**Extra Tips:** Use `arange` for quick array creation. Combine with `.reshape()` for multi-dimensional arrays.

In [13]:
a = np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# Slicing and Modifying Arrays
**Concept:** Slicing allows you to select and modify specific parts of an array.
**How it works:** `slice = a[0:5]` selects the first five elements. Multiplying `slice` by 10 updates those elements.
**Extra Tips:** Slicing creates a view, not a copy. Changes to the slice may affect the original array. Use `.copy()` for independent copies.

In [17]:
slice = a[0:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

# Viewing Modified Arrays
**Concept:** After modifying an array, it's important to view the result to verify changes.
**How it works:** Displaying `a` shows the current state of the array after slicing and modification.
**Extra Tips:** Use print statements or simply type the variable name in a notebook cell to view arrays.

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# Multiplying Array Slices
**Concept:** You can perform operations on specific slices of an array to modify only selected elements.
**How it works:** `a[4:6]*10` multiplies elements at indices 4 and 5 by 10.
**Extra Tips:** Slicing is zero-based and end-exclusive. Use slices for targeted modifications.

In [19]:
a[4:6]*10

array([50, 60])

# Shallow Copying Arrays
**Concept:** Assigning one array to another (e.g., `b = a`) creates a shallow copy, meaning both variables reference the same data.
**How it works:** Changes to `b` will also affect `a` because they point to the same memory location.
**Extra Tips:** Use `.copy()` for deep copies if you want independent arrays.

In [20]:
a
b = a


# Modifying Shallow Copies
**Concept:** Modifying a shallow copy affects the original array.
**How it works:** Changing `b[0]` also changes `a[0]` because both reference the same data.
**Extra Tips:** Always use `.copy()` if you need to preserve the original array.

In [22]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# Viewing Effects of Shallow Copy Modification
**Concept:** After modifying a shallow copy, viewing the original array shows the changes.
**How it works:** Displaying `a` after changing `b` confirms that both arrays are affected.
**Extra Tips:** Always check both arrays after modification to understand the impact of shallow copies.

In [23]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# Creating 2D Arrays for Matrix Operations
**Concept:** 2D arrays (matrices) are used for advanced mathematical operations like matrix multiplication.
**How it works:** `np.array([[1, 2], [3, 4]])` creates a 2x2 matrix. Multiple matrices can be created for operations.
**Extra Tips:** Ensure matrices have compatible shapes for multiplication and other operations.

In [27]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[6, 7], [9, 10]])

# Viewing Matrices
**Concept:** Displaying matrices helps verify their structure and values before performing operations.
**How it works:** Typing the variable name in a cell shows the matrix.
**Extra Tips:** Always check matrix shapes before operations.

In [28]:
a

array([[1, 2],
       [3, 4]])

# Viewing the Second Matrix
**Concept:** It's important to inspect both matrices before performing operations.
**How it works:** Displaying `b` shows the second matrix.
**Extra Tips:** Use print statements or notebook cells to view matrices.

In [29]:
b

array([[ 6,  7],
       [ 9, 10]])

# Matrix Multiplication with @ Operator
**Concept:** Matrix multiplication combines rows of the first matrix with columns of the second matrix to produce a new matrix.
**How it works:** `a @ b` multiplies matrix `a` by matrix `b` using the standard matrix multiplication rules.
**Extra Tips:** The number of columns in the first matrix must equal the number of rows in the second. Use `@` for readable code in Python 3.5+.

In [30]:
a @ b

array([[24, 27],
       [54, 61]])

# Matrix Multiplication with np.dot
**Concept:** `np.dot` is a NumPy function for matrix multiplication and dot products.
**How it works:** `np.dot(a, b)` multiplies matrix `a` by matrix `b`.
**Extra Tips:** Use `np.dot` for compatibility with older Python versions or when you need dot products for 1D arrays.

In [31]:
np.dot(a,b)

array([[24, 27],
       [54, 61]])

# Transposing Matrices
**Concept:** Transposing switches the rows and columns of a matrix.
**How it works:** `a.T` returns the transpose of matrix `a`.
**Extra Tips:** Transposing is useful for aligning data, preparing for matrix multiplication, and many linear algebra operations.

In [32]:
a.T

array([[1, 3],
       [2, 4]])

# Transposing the Second Matrix
**Concept:** Transposing is not limited to one matrix; you can transpose any array.
**How it works:** `b.T` returns the transpose of matrix `b`.
**Extra Tips:** Use transposes to match shapes for operations or to analyze data from different perspectives.

In [33]:
b.T

array([[ 6,  9],
       [ 7, 10]])

# Preparing Arrays for Stacking
**Concept:** Stacking combines multiple arrays into a single array along a specified axis.
**How it works:** Creating arrays `a` and `b` prepares them for stacking operations like vertical and horizontal stacking.
**Extra Tips:** Arrays must have compatible shapes for stacking.

In [34]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

# Vertical Stacking with np.vstack
**Concept:** Vertical stacking combines arrays as new rows in a single array.
**How it works:** `np.vstack((a, b))` stacks arrays `a` and `b` vertically, creating a 2D array.
**Extra Tips:** Use vertical stacking to combine datasets with the same number of columns.

In [37]:
np.vstack((a, b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Horizontal Stacking with np.hstack
**Concept:** Horizontal stacking combines arrays as new columns in a single array.
**How it works:** `np.hstack((a, b))` stacks arrays `a` and `b` horizontally, creating a longer 1D array or adding columns to a 2D array.
**Extra Tips:** Use horizontal stacking to merge features or data with the same number of rows.

In [38]:
np.hstack((a, b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Column Stacking with np.column_stack
**Concept:** Column stacking combines 1D arrays as columns in a 2D array.
**How it works:** `np.column_stack((a, b))` stacks arrays `a` and `b` as columns, creating a 2D array with each input as a column.
**Extra Tips:** Useful for creating feature matrices for machine learning.

In [39]:
np.column_stack((a, b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [40]:
c = np.arange(16).reshape(4,4)

In [41]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Summary: Array Splitting in NumPy
**Concept:** Splitting arrays is useful for dividing data into manageable parts for analysis, training, or visualization.
**How it works:** Use `np.hsplit` for horizontal (column-wise) splits and `np.vsplit` for vertical (row-wise) splits. Both require the number of splits to evenly divide the respective axis.
**Extra Tips:** Splitting is commonly used in machine learning for separating features and labels, or dividing datasets into batches.

# Splitting Arrays Horizontally with np.hsplit
**Concept:** Splitting divides an array into multiple sub-arrays along a specified axis. Horizontal splitting separates columns.
**How it works:** `np.hsplit(c, 2)` splits the array `c` into 2 equal sub-arrays along columns (axis 1). Each resulting array contains half the columns of the original.
**Extra Tips:** The number of splits must evenly divide the number of columns. Use horizontal splitting to separate features or data segments.

In [43]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# Splitting Arrays Vertically with np.vsplit
**Concept:** Vertical splitting divides an array into multiple sub-arrays along rows (axis 0).
**How it works:** `np.vsplit(c, 2)` splits the array `c` into 2 equal sub-arrays along rows. Each resulting array contains half the rows of the original.
**Extra Tips:** The number of splits must evenly divide the number of rows. Use vertical splitting to separate data samples or batches.

In [44]:
np.vsplit(c, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]