# Importing NumPy
NumPy is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and many mathematical functions.

The following code imports NumPy and gives it the alias `np` for convenience.

In [2]:
import numpy as np

# Creating a 1D NumPy Array
Here, a 1-dimensional NumPy array is created from a Python list. Arrays are the core data structure in NumPy and allow for efficient numerical operations.

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

# Creating a Python List
This step shows a regular Python list. Lists are flexible but do not support vectorized operations like NumPy arrays.

In [4]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

# Converting a List to a NumPy Array
This step converts the Python list `a` into a NumPy array, enabling efficient numerical operations.

In [5]:
np.array(a)


array([1, 2, 3, 4])

# Creating a Nested List for 2D Array
A nested list is used to represent a 2D structure (matrix) in Python. This can be converted to a 2D NumPy array for matrix operations.

In [57]:
l = [[1,2,3], [4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Converting Nested List to 2D NumPy Array
This step converts the nested list `l` into a 2D NumPy array, which is useful for matrix operations and numerical computations.

In [9]:
np.array(l)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Creating Arrays with np.arange
`np.arange(start, stop)` creates a 1D array with values starting from `start` up to (but not including) `stop`. This is useful for generating sequences of numbers.

In [18]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Using np.arange with a Step
You can specify a step value in `np.arange(start, stop, step)` to control the increment between values. This is useful for generating sequences with custom intervals.

In [19]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

# Creating an Array of Zeros
`np.zeros(shape)` creates an array filled with zeros. The `shape` parameter defines the dimensions of the array. This is useful for initializing arrays before filling them with data.

In [20]:
arr  = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Creating an Array of Ones
`np.ones(shape)` creates an array filled with ones. This is often used for initialization or as a starting point for further operations.

In [22]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Creating Evenly Spaced Values with np.linspace
`np.linspace(start, stop, num)` generates `num` evenly spaced values between `start` and `stop` (inclusive). This is useful for creating ranges for plotting or sampling.

In [27]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

# Generating More Evenly Spaced Values
By increasing the `num` parameter in `np.linspace`, you can generate more points, which is useful for high-resolution sampling or plotting.

In [28]:
arr = np.linspace(1,5,100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

# Generating Random Numbers with np.random.rand
`np.random.rand(n)` generates `n` random numbers from a uniform distribution over [0, 1). Useful for simulations and initializing random data.

In [30]:
np.random.rand(10)

array([0.43828553, 0.98745337, 0.08493871, 0.62840778, 0.05472672,
       0.28422195, 0.02879688, 0.60972717, 0.02635631, 0.56767995])

# generating Random Numbers from a Normal Distribution
`np.random.randn(n)` generates `n` random numbers from the standard normal distribution (mean 0, standard deviation 1). Useful for statistical simulations.

In [33]:
np.random.randn(10)

array([ 0.31112964, -0.47067253, -0.38584738,  1.22409778,  0.58534266,
        0.53528449, -0.40949806, -0.5938633 , -0.44167557, -1.29756988])

# Generating Random Integers
`np.random.randint(low, high, size)` generates random integers between `low` (inclusive) and `high` (exclusive). Useful for creating random datasets or indices.

In [35]:
np.random.randint(10,20,10)

array([17, 15, 19, 12, 13, 15, 19, 11, 16, 16], dtype=int32)

# Creating a 2D Array (Matrix)
You can create a 2D array (matrix) by passing a nested list to `np.array`. This is useful for representing tabular data or performing matrix operations.

In [36]:
arr = np.array([[1,2,3], [4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Checking the Shape of an Array
The `.shape` attribute returns a tuple representing the dimensions of the array (rows, columns for 2D arrays).

In [37]:
arr.shape

(3, 3)

# Checking the Size of an Array
The `.size` attribute returns the total number of elements in the array, regardless of its shape.

In [38]:
arr.size

9

# Checking the Data Type of Array Elements
The `.dtype` attribute shows the data type of the elements stored in the array (e.g., int32, float64).

In [39]:
arr.dtype

dtype('int64')

# Viewing the Array
Simply outputting the array variable displays its contents, which is useful for inspection and debugging.

In [40]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Finding the Minimum Value
The `.min()` method returns the smallest value in the array.

In [42]:
arr.min()

np.int64(1)

# Finding the Maximum Value
The `.max()` method returns the largest value in the array.

In [43]:
arr.max()

np.int64(9)

# Summing All Elements
The `.sum()` method returns the sum of all elements in the array.

In [44]:
arr.sum()

np.int64(45)

# Summing Along Columns (axis=0)
`np.sum(arr, axis=0)` sums the elements of the array along each column. Axis-based operations are useful for aggregating data across specific dimensions.

In [45]:
np.sum(arr,axis=0)

array([12, 15, 18])

# Summing Along Rows (axis=1)
`np.sum(arr, axis=1)` sums the elements of the array along each row. This is useful for row-wise aggregation.

In [46]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

# Calculating the Mean
The `.mean()` method returns the average value of all elements in the array.

In [47]:
arr.mean()

np.float64(5.0)

# Standardization and Normalization
**Standardization** is the process of transforming data to have a mean of 0 and a standard deviation of 1. This is often done using the formula:

    standardized_value = (value - mean) / std

**Normalization** typically means scaling data to a fixed range, usually [0, 1], using the formula:

    normalized_value = (value - min) / (max - min)

Standardization is useful when you want to compare data with different scales or units, and is commonly used in machine learning. The `.std()` method is used to calculate the standard deviation, which is a key part of standardization.

# Calculating the Standard Deviation
The `.std()` method returns the standard deviation, a measure of the spread of the array's values.

In [48]:
arr.std()

np.float64(2.581988897471611)

# Finding the Index of the Maximum Value
The `.argmax()` method returns the index of the first occurrence of the maximum value in the array.

In [49]:
arr.argmax()

np.int64(8)

# Finding the Index of the Minimum Value
The `.argmin()` method returns the index of the first occurrence of the minimum value in the array.

In [50]:
arr.argmin()

np.int64(0)

# Creating a 1D Array from 1 to 30
`np.arange(1,31)` creates a 1D array with values from 1 to 30. This is often used as a starting point for reshaping or further operations.

In [53]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

#  Reshaping the Array
The `.reshape(new_shape)` method changes the shape of the array without changing its data. Here, the 1D array is reshaped into a 6x5 matrix.

In [56]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])